name: CI for Docker with ECR

on:
  push:
    branches:
      - master  # Change to 'main' if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3  # Updated to v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ap-south-1  # Make sure this matches your AWS region

      - name: Build Docker image
        run: |
          docker build -t cafe .
        
      - name: Tag Docker image for ECR
        run: |
          docker tag cafe:latest 369668972483.dkr.ecr.ap-south-1.amazonaws.com/cafe:latest

      - name: Push Docker image to ECR
        run: |
          docker push 369668972483.dkr.ecr.ap-south-1.amazonaws.com/cafe:latest
